#!/bin/bash

keybase login

for f in $*
do
  echo "Decrypting" $f "to" ${f%.*}
  echo "--------------------------------------------------------------------------------"
  keybase pgp decrypt -i $f -o ${f%.*}
  echo "--------------------------------------------------------------------------------"
  echo $f "decrypted" "to" ${f%.*}
done
