#!/bin/bash

keybase login

for f in "$*"
do
  echo "Decrypting" $f
  echo "--------------------------------------------------------------------------------"
  cat $f | keybase decrypt
  echo "--------------------------------------------------------------------------------"
  echo $f "decrypted"
done
